'use client';

import { useState, useEffect } from 'react';
import { useAuth } from '@/hooks/use-auth';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Card, CardContent, CardDescription, CardHeader, CardTitle, CardFooter } from '@/components/ui/card';
import { Label } from '@/components/ui/label';
import { Alert, AlertDescription, AlertTitle } from '@/components/ui/alert';
import { Shield, Smartphone, Lock, CheckCircle2, AlertCircle, Loader2 } from 'lucide-react';
import { generateTwoFactorSecret, enableTwoFactor, disableTwoFactor, getUserStatus } from '@/services/cec'; // We need verifyUserPassword to re-auth before disable? Maybe overkill for now, but good practice.
import QRCode from 'qrcode'; // Client side QR generation or Server? Service returns otpauth URL.
// We should import qrcode on client or use an image generated by server?
// generateTwoFactorSecret returns { secret, otpauth }.
// We can use 'qrcode' package on client to render the otpauth url.

import { useToast } from '@/hooks/use-toast';

export function UserSecuritySettings() {
    const { user } = useAuth();
    const { toast } = useToast();

    // State
    const [is2FAEnabled, setIs2FAEnabled] = useState(false);
    const [isLoading, setIsLoading] = useState(true);

    // Setup State
    const [setupStep, setSetupStep] = useState<'idle' | 'qr' | 'verify'>('idle');
    const [secretData, setSecretData] = useState<{ secret: string; otpauth: string } | null>(null);
    const [qrCodeUrl, setQrCodeUrl] = useState('');
    const [verifyCode, setVerifyCode] = useState('');
    const [setupError, setSetupError] = useState('');
    const [setupLoading, setSetupLoading] = useState(false);

    // Initial check
    useEffect(() => {
        const checkStatus = async () => {
            if (!user?.username) {
                setIsLoading(false);
                return;
            }
            try {
                const status = await getUserStatus(user.username);
                if (status) {
                    setIs2FAEnabled(status.isTwoFactorEnabled);
                }
            } catch (e) {
                console.error(e);
            } finally {
                setIsLoading(false);
            }
        };
        checkStatus();
    }, [user]);

    // But wait, I added 'verifyTwoFactor' which checks it. 
    // Maybe I can just use that to "check" if I have a token? No.

    // Let's implement the "Enable" flow.

    const handleStartSetup = async () => {
        if (!user?.username) return;
        setSetupLoading(true);
        setSetupError('');
        try {
            const data = await generateTwoFactorSecret(user.username);
            setSecretData(data);
            const url = await QRCode.toDataURL(data.otpauth);
            setQrCodeUrl(url);
            setSetupStep('verify');
        } catch (error: any) {
            setSetupError("Impossible de générer le secret 2FA.");
        } finally {
            setSetupLoading(false);
        }
    };

    const handleVerifyAndEnable = async () => {
        if (!user?.username || !secretData) return;
        setSetupLoading(true);
        setSetupError('');
        try {
            await enableTwoFactor(user.username, secretData.secret, verifyCode);
            setIs2FAEnabled(true);
            setSetupStep('idle');
            setSecretData(null);
            setVerifyCode('');
            toast({
                title: "Sécurité mise à jour",
                description: "L'authentification à deux facteurs est maintenant activée.",
                variant: "default", // Success
            });
        } catch (error: any) {
            setSetupError("Code incorrect. Veuillez réessayer.");
        } finally {
            setSetupLoading(false);
        }
    };

    const handleDisable = async () => {
        if (!user?.username) return;
        if (!confirm("Êtes-vous sûr de vouloir désactiver la double authentification ? Votre compte sera moins sécurisé.")) return;

        setSetupLoading(true);
        try {
            await disableTwoFactor(user.username);
            setIs2FAEnabled(false);
            toast({
                title: "Sécurité mise à jour",
                description: "L'authentification à deux facteurs a été désactivée.",
                variant: "destructive",
            });
        } catch (error) {
            toast({
                title: "Erreur",
                description: "Impossible de désactiver la 2FA.",
                variant: "destructive"
            });
        } finally {
            setSetupLoading(false);
        }
    };

    if (isLoading) {
        return <div>Chargement...</div>;
    }

    return (
        <Card>
            <CardHeader>
                <div className="flex items-center gap-3">
                    <Shield className="h-6 w-6 text-primary" />
                    <CardTitle>Authentification à Deux Facteurs (2FA)</CardTitle>
                </div>
                <CardDescription>
                    Ajoutez une couche de sécurité supplémentaire à votre compte en utilisant une application d'authentification (comme Google Authenticator ou Authy).
                </CardDescription>
            </CardHeader>
            <CardContent className="space-y-6">

                {/* Status Indicator */}
                <div className="flex items-center justify-between p-4 border rounded-lg bg-muted/30">
                    <div className="flex items-center gap-3">
                        <div className={`h-10 w-10 rounded-full flex items-center justify-center ${is2FAEnabled ? 'bg-green-100 text-green-600' : 'bg-yellow-100 text-yellow-600'}`}>
                            {is2FAEnabled ? <CheckCircle2 className="h-6 w-6" /> : <Lock className="h-6 w-6" />}
                        </div>
                        <div>
                            <p className="font-medium">{is2FAEnabled ? 'Activé' : 'Désactivé'}</p>
                            <p className="text-sm text-muted-foreground">{is2FAEnabled ? 'Votre compte est protégé.' : 'Votre compte est vulnérable.'}</p>
                        </div>
                    </div>

                    {!is2FAEnabled && setupStep === 'idle' && (
                        <Button onClick={handleStartSetup} disabled={setupLoading}>
                            Activer
                        </Button>
                    )}

                    {is2FAEnabled && (
                        <Button variant="outline" onClick={handleDisable} disabled={setupLoading} className="text-destructive hover:text-destructive">
                            Désactiver
                        </Button>
                    )}
                </div>

                {/* Setup Flow */}
                {!is2FAEnabled && setupStep === 'verify' && (
                    <div className="border rounded-lg p-6 space-y-6 animate-in slide-in-from-top-4">
                        <div className="text-center space-y-2">
                            <h3 className="font-semibold text-lg">Configurer Google Authenticator</h3>
                            <p className="text-sm text-muted-foreground">Scannez ce QR code avec votre application.</p>
                        </div>

                        <div className="flex justify-center bg-white p-4 rounded-xl border w-fit mx-auto">
                            {qrCodeUrl ? (
                                <img src={qrCodeUrl} alt="2FA QR Code" className="w-48 h-48" />
                            ) : (
                                <div className="w-48 h-48 flex items-center justify-center"><Loader2 className="animate-spin" /></div>
                            )}
                        </div>

                        <div className="space-y-4 max-w-xs mx-auto">
                            <div className="space-y-2">
                                <Label htmlFor="verify-code">Code de vérification</Label>
                                <Input
                                    id="verify-code"
                                    placeholder="000 000"
                                    className="text-center text-lg tracking-widest"
                                    maxLength={6}
                                    value={verifyCode}
                                    onChange={(e) => setVerifyCode(e.target.value)}
                                />
                            </div>

                            {setupError && (
                                <Alert variant="destructive">
                                    <AlertCircle className="h-4 w-4" />
                                    <AlertDescription>{setupError}</AlertDescription>
                                </Alert>
                            )}

                            <div className="flex gap-2">
                                <Button variant="ghost" className="flex-1" onClick={() => setSetupStep('idle')}>Annuler</Button>
                                <Button className="flex-1" onClick={handleVerifyAndEnable} disabled={setupLoading || verifyCode.length < 6}>
                                    {setupLoading && <Loader2 className="mr-2 h-4 w-4 animate-spin" />}
                                    Vérifier
                                </Button>
                            </div>
                        </div>
                    </div>
                )}

            </CardContent>
        </Card>
    );
}
